## Demographic Data Analysis

In [22]:
#Imports required libraries
import geopandas as gpd

In [23]:
#Imports population shapefile
data_path=r"D:\GIS-TU Dublin\Year_2\THESIS\DCC_Analysis"
shape_file_path= data_path + r"\Data_used\Population_DCC\Population_Small_Areas_DCC.shp"

In [28]:
pop_gdf= gpd.read_file(shape_file_path)

In [34]:
pop_gdf.head()

                                   GUID  ...                                           geometry
0  4c07d11e-3b4c-851d-e053-ca3ca8c0ca7f  ...  POLYGON ((714810.211 734199.213, 714775.416 73...
1  4c07d11e-3955-851d-e053-ca3ca8c0ca7f  ...  POLYGON ((711572.517 733692.733, 711390.348 73...
2  4c07d11e-3453-851d-e053-ca3ca8c0ca7f  ...  POLYGON ((714629.209 731596.905, 714634.897 73...
3  4c07d11e-3884-851d-e053-ca3ca8c0ca7f  ...  POLYGON ((715772.776 735657.239, 715818.326 73...
4  4c07d11e-39fb-851d-e053-ca3ca8c0ca7f  ...  POLYGON ((715290.725 732613.811, 715226.910 73...

[5 rows x 147 columns]

In [35]:
# List all column names
for col in pop_gdf.columns:
    print(col)

GUID
GEOGID
GEOGDESC
Reference_
SA_PUB2022
SA_GEOGID_
BUA_GUID
BUA_CODE
BUA_NAME
ED_GUID
ED_ID_STR
ED_ENGLISH
ED_GAEILGE
ED_OFFICIA
LEA_GUID
CSO_LEA
LEA_ID
LEA_OFFICI
LA_GUID
LOCAL_AUTH
LA_CODE
COUNTY
CONTAE
PROVINCE
NUTS3
NUTS3_NAME
NUTS2
NUTS2_NAME
NUTS1
NUTS1_NAME
T1_1AGETF_
T1_1AGETM_
T1_1AGETT_
T6_8_O_Nor
T6_8_TA_No
T6_8_UHH_N
T6_8_OVD_N
T6_8_T_Nor
AREA
AREA_UOM
GUID_17011
T1_1AGE0M
T1_1AGE1M
T1_1AGE2M
T1_1AGE3M
T1_1AGE4M
T1_1AGE5M
T1_1AGE6M
T1_1AGE7M
T1_1AGE8M
T1_1AGE9M
T1_1AGE10M
T1_1AGE11M
T1_1AGE12M
T1_1AGE13M
T1_1AGE14M
T1_1AGE15M
T1_1AGE16M
T1_1AGE17M
T1_1AGE18M
T1_1AGE19M
T1_1AGE20_
T1_1AGE25_
T1_1AGE30_
T1_1AGE35_
T1_1AGE40_
T1_1AGE45_
T1_1AGE50_
T1_1AGE55_
T1_1AGE60_
T1_1AGE65_
T1_1AGE70_
T1_1AGE75_
T1_1AGE80_
T1_1AGEGE_
T1_1AGETM
T1_1AGE0F
T1_1AGE1F
T1_1AGE2F
T1_1AGE3F
T1_1AGE4F
T1_1AGE5F
T1_1AGE6F
T1_1AGE7F
T1_1AGE8F
T1_1AGE9F
T1_1AGE10F
T1_1AGE11F
T1_1AGE12F
T1_1AGE13F
T1_1AGE14F
T1_1AGE15F
T1_1AGE16F
T1_1AGE17F
T1_1AGE18F
T1_1AGE19F
T1_1AGE201
T1_1AGE251
T1_1AGE301
T1_1AGE351
T1_1AGE401
T1_1AGE451
T1_1AGE501
T1_1AGE551
T1_1AGE601
T1_1AGE651
T1_1AGE701
T1_1AGE751
T1_1AGE801
T1_1AGEGE1
T1_1AGETF
T1_1AGE0T
T1_1AGE1T
T1_1AGE2T
T1_1AGE3T
T1_1AGE4T
T1_1AGE5T
T1_1AGE6T
T1_1AGE7T
T1_1AGE8T
T1_1AGE9T
T1_1AGE10T
T1_1AGE11T
T1_1AGE12T
T1_1AGE13T
T1_1AGE14T
T1_1AGE15T
T1_1AGE16T
T1_1AGE17T
T1_1AGE18T
T1_1AGE19T
T1_1AGE2_1
T1_1AGE2_2
T1_1AGE3_1
T1_1AGE3_2
T1_1AGE4_1
T1_1AGE4_2
T1_1AGE5_1
T1_1AGE5_2
T1_1AGE6_1
T1_1AGE6_2
T1_1AGE7_1
T1_1AGE7_2
T1_1AGE8_1
T1_1AGEG_1
T1_1AGETT
geometry

In [42]:
# Keep only relevant columns
keep_cols = [ "SA_PUB2022", "GEOGDESC", "LA_CODE", "COUNTY", "AREA","CSO_LEA","LEA_ID",
    "T1_1AGETT", "T1_1AGE65_", "T1_1AGE70_", "T1_1AGE75_", 
    "T1_1AGE80_", "T1_1AGEGE_", "geometry"
]
pop_gdf_filter = pop_gdf[keep_cols]

In [43]:
pop_gdf_filter.head()

     SA_PUB2022  ...                                           geometry
0     268098009  ...  POLYGON ((714810.211 734199.213, 714775.416 73...
1     268083012  ...  POLYGON ((711572.517 733692.733, 711390.348 73...
2     268144014  ...  POLYGON ((714629.209 731596.905, 714634.897 73...
3  268138009/01  ...  POLYGON ((715772.776 735657.239, 715818.326 73...
4     268162014  ...  POLYGON ((715290.725 732613.811, 715226.910 73...

[5 rows x 14 columns]

In [66]:
# Rename selected columns to simpler names
rename_map = {
    "SA_PUB2022": "SA_ID",
    "GEOGDESC": "SA_Name",
    "T1_1AGETT": "TotalPop",
    "T1_1AGE65_": "Age65_69",
    "T1_1AGE70_": "Age70_74",
    "T1_1AGE75_": "Age75_79",
    "T1_1AGE80_": "Age80_84",
    "T1_1AGEGE_": "Age85plus",
}
renamed_pop_gdf = pop_gdf_filter.rename(columns=rename_map)
renamed_pop_gdf.head()

          SA_ID  ...                                           geometry
0     268098009  ...  POLYGON ((714810.211 734199.213, 714775.416 73...
1     268083012  ...  POLYGON ((711572.517 733692.733, 711390.348 73...
2     268144014  ...  POLYGON ((714629.209 731596.905, 714634.897 73...
3  268138009/01  ...  POLYGON ((715772.776 735657.239, 715818.326 73...
4     268162014  ...  POLYGON ((715290.725 732613.811, 715226.910 73...

[5 rows x 14 columns]

In [69]:
# Calculate total elderly population (65+)
renamed_pop_gdf["T_65Plus"] = (
    renamed_pop_gdf["Age65_69"] +
    renamed_pop_gdf["Age70_74"] +
    renamed_pop_gdf["Age75_79"] +
    renamed_pop_gdf["Age80_84"] +
    renamed_pop_gdf["Age85plus"]
)

# Calculate percentage of elderly in each Small Area
renamed_pop_gdf["ElderlyPct"] = (renamed_pop_gdf["T_65Plus"] / renamed_pop_gdf["TotalPop"]) * 100

In [70]:
renamed_pop_gdf.head()

          SA_ID       SA_Name LA_CODE  ... Elderly65plus  T_65Plus ElderlyPct
0     268098009     268098009      DC  ...             6         6   2.362205
1     268083012     268083012      DC  ...             6         6   2.429150
2     268144014     268144014      DC  ...            12        12   7.017544
3  268138009/01  268138009/01      DC  ...             6         6   1.662050
4     268162014     268162014      DC  ...             7         7   4.268293

[5 rows x 17 columns]

In [71]:
# Save renamed_pop_gdf as a shapefile
renamed_pop_gdf.to_file(data_path + r"\Data_used\Population_DCC\ElderlyPop.shp", driver="ESRI Shapefile", encoding="utf-8")

[71]:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.