In [ ]:
import csv
import os
import pandas as pd
import os

# Conversion of .txt file to .csv file

In [12]:
#Conversion of .txt file to .csv file


# Define input and output directories
input_dir = r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_txt'
output_dir = r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv'

# Create the output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Define the delimiter used in the .txt files
delimiter = ','

# Iterate through all .txt files in the input directory
for filename in os.listdir(input_dir):
    if filename.endswith('.txt'):
        # Define the full paths for input and output files
        input_txt_file = os.path.join(input_dir, filename)
        output_csv_file = os.path.join(output_dir, filename.replace('.txt', '.csv'))

        # Open the .txt file for reading and the .csv file for writing
        try:
            with open(input_txt_file, 'r',encoding='utf-8') as txt_file, open(output_csv_file, 'w', newline='',encoding='utf-8') as csv_file:
                # Create a CSV writer object
                csv_writer = csv.writer(csv_file)
                
                # Read each line from the .txt file
                for line in txt_file:
                    # Split the line into columns based on the delimiter
                    row = line.strip().split(delimiter)
                    
                    # Write the row to the CSV file
                    csv_writer.writerow(row)

            print(f"Converted {filename} to {output_csv_file}")
        except PermissionError:
            print(f"Permission denied: Could not process {filename}.")
        except Exception as e:
            print(f"An error occurred while processing {filename}: {e}")

print("All conversions complete.")

Converted agency.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\agency.csv
Converted calendar.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\calendar.csv
Converted calendar_dates.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\calendar_dates.csv
Converted feed_info.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\feed_info.csv
Converted routes.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\routes.csv
Converted shapes.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\shapes.csv
Converted stops.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\stops.csv
Converted stop_times.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\stop_times.csv
Converted trips.txt to D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\trips.csv
All conversions complete.

# 1.Checking stops.csv dataset

In [17]:
#1.checking stops.csv dataset

import pandas as pd

# Load the stops.csv file
stops_df = pd.read_csv(r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\stops.csv')

Analyzing stops.csv
==================================================

In [25]:
#Display the first few rows
print("\nFirst 5 rows:")
stops_df.head()

First 5 rows:

,"""stop_id""","""stop_code""","""stop_name""","""stop_lat""","""stop_lon""","""zone_id""","""stop_url""","""location_type""","""parent_station""","""stop_desc""","""stop_timezone""","""wheelchair_boarding""","""level_id""","""platform_code"""
0,"""15-822008203""","""8203""","""Visitor Centre""","""53.36469""","""-6.33167""","""""","""""","""0""","""""","""""","""""","""0""","""""",""""""
1,"""15-822008204""","""8204""","""Áras an Uachtaráin""","""53.35969""","""-6.32456""","""""","""""","""0""","""""","""""","""""","""0""","""""",""""""
2,"""15-822008205""","""8205""","""Dublin Zoo""","""53.35173""","""-6.30548""","""""","""""","""0""","""""","""""","""""","""0""","""""",""""""
3,"""15-822008206""","""8206""","""Park Gates""","""53.34884""","""-6.29777""","""""","""""","""0""","""""","""""","""""","""0""","""""",""""""
4,"""15-822008208""","""8208""","""Park Gates""","""53.34872""","""-6.29792""","""""","""""","""0""","""""","""""","""""","""0""","""""",""""""

In [40]:
stops_df.columns

Index(['"stop_id"', '"stop_code"', '"stop_name"', '"stop_lat"', '"stop_lon"',
       '"zone_id"', '"stop_url"', '"location_type"', '"parent_station"',
       '"stop_desc"', '"stop_timezone"', '"wheelchair_boarding"', '"level_id"',
       '"platform_code"'],
      dtype='object')

In [32]:

# Check if the columns 'stop_id', 'stop_code', 'stop_name', 'stop_lat', 'stop_lon' have any missing or empty values
columns_to_check = ['"stop_id"', '"stop_code"', '"stop_name"', '"stop_lat"', '"stop_lon"']

# Find rows with empty or missing values in these columns
missing_values = stops_df[columns_to_check].isnull() | (stops_df[columns_to_check] == "")
# Filter rows where any of the specified columns have missing or empty values
rows_with_missing_values = stops_df[missing_values.any(axis=1)]

# Output the rows with missing or empty values
if not rows_with_missing_values.empty:
    print(f"Rows with missing or empty values in any of the columns {columns_to_check}:")
    print(rows_with_missing_values)
else:
    print("No missing or empty values found in the specified columns.")

No missing or empty values found in the specified columns.

In [22]:
 #Check for duplicates
print("\nNumber of duplicate rows:")
print(stops_df.duplicated().sum())

Number of duplicate rows:
0

# 2.Checking trips.csv dataset

In [37]:
# Load the trips.csv file
trips_df = pd.read_csv(r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\trips.csv')

In [38]:
#Display the first few rows
print("\nFirst 5 rows:")
trips_df.head()

First 5 rows:

,"""route_id""","""service_id""","""trip_id""","""trip_headsign""","""trip_short_name""","""direction_id""","""block_id""","""shape_id""","""wheelchair_accessible""","""bikes_allowed"""
0,"""15-3941_63061""","""15-173""","""15-2945271020a43c8499f7""","""Shaw street""","""5875""","""0""","""3941_7778195_9001001""","""15-3941_1""","""""",""""""
1,"""15-3941_63061""","""15-173""","""15-f43222920e5ec95f283c""","""Shaw street""","""5935""","""0""","""3941_7778195_9001009""","""15-3941_1""","""""",""""""
2,"""15-3941_63061""","""15-111""","""15-431a4f883d44ca7a133b""","""Shaw street""","""12521""","""0""","""3941_7778195_9001003""","""15-3941_1""","""""",""""""
3,"""15-3941_63057""","""15-173""","""15-3c13449ea6d293f98c0a""","""Ashington""","""7891""","""1""","""3941_7778195_7122021""","""15-3941_33""","""""",""""""
4,"""15-3941_63014""","""15-111""","""15-a6ba15a9a825c4945816""","""Abbey St""","""13146""","""1""","""3941_7778195_5041004""","""15-3941_318""","""""",""""""

In [42]:
trips_df.columns

Index(['"route_id"', '"service_id"', '"trip_id"', '"trip_headsign"',
       '"trip_short_name"', '"direction_id"', '"block_id"', '"shape_id"',
       '"wheelchair_accessible"', '"bikes_allowed"'],
      dtype='object')

In [44]:
# Check if the columns route_id, service_id, trip_id, trip_headsign, trip_short_name, direction_id, block_id, shape_id have any missing or empty values
columns_to_check = ['"route_id"', '"service_id"', '"trip_id"', '"trip_headsign"', '"trip_short_name"','"direction_id"','"block_id"','"shape_id"']

# Find rows with empty or missing values in these columns
missing_values = trips_df[columns_to_check].isnull() | (trips_df[columns_to_check] == "")
# Filter rows where any of the specified columns have missing or empty values
rows_with_missing_values = trips_df[missing_values.any(axis=1)]

# Output the rows with missing or empty values
if not rows_with_missing_values.empty:
    print(f"Rows with missing or empty values in any of the columns {columns_to_check}:")
    print(rows_with_missing_values)
else:
    print("No missing or empty values found in the specified columns.")

No missing or empty values found in the specified columns.

In [45]:
 #Check for duplicates
print("\nNumber of duplicate rows:")
print(trips_df.duplicated().sum())

Number of duplicate rows:
0

# 3.Checking routes.csv dataset

In [49]:
# Load the routes.csv file
routes_df = pd.read_csv(r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\routes.csv')

In [50]:
#Display the first few rows
print("\nFirst 5 rows:")
routes_df.head()

First 5 rows:

,"""route_id""","""agency_id""","""route_short_name""","""route_long_name""","""route_desc""","""route_type""","""route_url""","""route_color""","""route_text_color""","""route_sort_order""","""continuous_pickup""","""continuous_drop_off"""
0,"""15-3941_62982""","""15-7778019""","""4""","""Monkstown Avenue - Harristown""","""""","""3""","""""","""F2CA36""","""000000""","""""","""""",""""""
1,"""15-3941_62983""","""15-7778019""","""6""","""Howth Dart Stn - Lower Abbey Street""","""""","""3""","""""","""F2CA36""","""000000""","""""","""""",""""""
2,"""15-3941_62984""","""15-7778019""","""11""","""Sandyford Ind Estate - Wadelai Pk""","""""","""3""","""""","""F2CA36""","""000000""","""""","""""",""""""
3,"""15-3941_62985""","""15-7778019""","""13""","""Grange Castle - Harristown""","""""","""3""","""""","""F2CA36""","""000000""","""""","""""",""""""
4,"""15-3941_62986""","""15-7778019""","""14""","""Dundrum Luas Stn - Ardlea Rd (Beaumont)""","""""","""3""","""""","""F2CA36""","""000000""","""""","""""",""""""

In [51]:
routes_df.columns

Index(['"route_id"', '"agency_id"', '"route_short_name"', '"route_long_name"',
       '"route_desc"', '"route_type"', '"route_url"', '"route_color"',
       '"route_text_color"', '"route_sort_order"', '"continuous_pickup"',
       '"continuous_drop_off"'],
      dtype='object')

In [54]:
# Check if the columns route_id, agency_id, route_short_name, route_long_name,route_type
columns_to_check = ['"route_id"', '"agency_id"', '"route_short_name"', '"route_long_name"', '"route_type"']

# Find rows with empty or missing values in these columns
missing_values = routes_df[columns_to_check].isnull() | (routes_df[columns_to_check] == "")
# Filter rows where any of the specified columns have missing or empty values
rows_with_missing_values = routes_df[missing_values.any(axis=1)]

# Output the rows with missing or empty values
if not rows_with_missing_values.empty:
    print(f"Rows with missing or empty values in any of the columns {columns_to_check}:")
    print(rows_with_missing_values)
else:
    print("No missing or empty values found in the specified columns.")

No missing or empty values found in the specified columns.

In [55]:
 #Check for duplicates
print("\nNumber of duplicate rows:")
print(routes_df.duplicated().sum())

Number of duplicate rows:
0

# 4.Checking shapes.csv file

In [58]:
# Load the shapes.csv file
shapes_df = pd.read_csv(r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\shapes.csv')

In [59]:
#Display the first few rows
print("\nFirst 5 rows:")
shapes_df.head()

First 5 rows:

,"""shape_id""","""shape_pt_lat""","""shape_pt_lon""","""shape_pt_sequence""","""shape_dist_traveled"""
0,"""15-3941_1""","""53.391182""","""-6.262196""","""0""","""0"""
1,"""15-3941_1""","""53.391191""","""-6.262389""","""1""","""12.8"""
2,"""15-3941_1""","""53.391808""","""-6.262357""","""2""","""81.5"""
3,"""15-3941_1""","""53.391869""","""-6.262374""","""3""","""88.4"""
4,"""15-3941_1""","""53.391886""","""-6.2616""","""4""","""139.8"""

In [61]:
shapes_df.columns

Index(['"shape_id"', '"shape_pt_lat"', '"shape_pt_lon"', '"shape_pt_sequence"',
       '"shape_dist_traveled"'],
      dtype='object')

In [69]:
# Check if the columns shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled
columns_to_check = ['"shape_id"', '"shape_pt_lat"','"shape_pt_lon"' ,'"shape_pt_sequence"', '"shape_dist_traveled"']

# Find rows with empty or missing values in these columns
missing_values = shapes_df[columns_to_check].isnull() | (shapes_df[columns_to_check] == "")
# Filter rows where any of the specified columns have missing or empty values
rows_with_missing_values = shapes_df[missing_values.any(axis=1)]

# Output the rows with missing or empty values
if not rows_with_missing_values.empty:
    print(f"Rows with missing or empty values in any of the columns {columns_to_check}:")
    print(rows_with_missing_values)
else:
    print("No missing or empty values found in the specified columns.")

No missing or empty values found in the specified columns.

In [64]:
 #Check for duplicates
print("\nNumber of duplicate rows:")
print(shapes_df.duplicated().sum())

Number of duplicate rows:
0

# 5.Checking stop_times.csv

In [66]:
# Load the stop_times.csv file
stop_times_df = pd.read_csv(r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\stop_times.csv')

In [67]:
#Display the first few rows
print("\nFirst 5 rows:")
stop_times_df.head()

First 5 rows:

,"""trip_id""","""arrival_time""","""departure_time""","""stop_id""","""stop_sequence""","""stop_headsign""","""pickup_type""","""drop_off_type""","""continuous_pickup""","""continuous_drop_off""","""shape_dist_traveled""","""timepoint"""
0,"""15-2945271020a43c8499f7""","""06:30:00""","""06:30:00""","""15-8240DB000226""","""0""","""Shaw street""","""0""","""1""","""""","""""","""""","""1"""
1,"""15-2945271020a43c8499f7""","""06:31:04""","""06:31:04""","""15-8220DB000228""","""1""","""""","""0""","""0""","""""","""""","""""","""1"""
2,"""15-2945271020a43c8499f7""","""06:31:59""","""06:31:59""","""15-8240DB000229""","""2""","""""","""0""","""0""","""""","""""","""""","""1"""
3,"""15-2945271020a43c8499f7""","""06:33:24""","""06:33:24""","""15-8240DB000227""","""3""","""""","""0""","""0""","""""","""""","""""","""1"""
4,"""15-2945271020a43c8499f7""","""06:34:19""","""06:34:19""","""15-8240DB000230""","""4""","""""","""0""","""0""","""""","""""","""""","""1"""

In [68]:
stop_times_df.columns

Index(['"trip_id"', '"arrival_time"', '"departure_time"', '"stop_id"',
       '"stop_sequence"', '"stop_headsign"', '"pickup_type"',
       '"drop_off_type"', '"continuous_pickup"', '"continuous_drop_off"',
       '"shape_dist_traveled"', '"timepoint"'],
      dtype='object')

In [70]:
# Check the columns trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type
columns_to_check = ['"trip_id"', '"arrival_time"','"departure_time"' ,'"stop_id"', '"stop_sequence"','"stop_headsign"','"pickup_type"','"drop_off_type"']

# Find rows with empty or missing values in these columns
missing_values = stop_times_df[columns_to_check].isnull() | (stop_times_df[columns_to_check] == "")
# Filter rows where any of the specified columns have missing or empty values
rows_with_missing_values = stop_times_df[missing_values.any(axis=1)]

# Output the rows with missing or empty values
if not rows_with_missing_values.empty:
    print(f"Rows with missing or empty values in any of the columns {columns_to_check}:")
    print(rows_with_missing_values)
else:
    print("No missing or empty values found in the specified columns.")

No missing or empty values found in the specified columns.

In [71]:
 #Check for duplicates
print("\nNumber of duplicate rows:")
print(stop_times_df.duplicated().sum())

Number of duplicate rows:
0

# 6.Checking calendar.csv

In [72]:
# Load the calender.csv file
calendar_df = pd.read_csv(r'D:\GIS-TU Dublin\Year_2\Research_Proj_Dissertation\Thesis Proposal\data\data_check\DublinBus_GTFS_csv\calendar.csv')

In [73]:
#Display the first few rows
print("\nFirst 5 rows:")
calendar_df.head()

First 5 rows:

,"""service_id""","""monday""","""tuesday""","""wednesday""","""thursday""","""friday""","""saturday""","""sunday""","""start_date""","""end_date"""
0,"""15-111""","""0""","""0""","""0""","""0""","""0""","""1""","""0""","""20240330""","""20240629"""
1,"""15-173""","""1""","""1""","""1""","""1""","""1""","""0""","""0""","""20240402""","""20240628"""
2,"""15-174""","""0""","""0""","""0""","""0""","""0""","""0""","""1""","""20240331""","""20240623"""